name: Compile SHiELD SOLO and run tests

on:
  pull_request:
    branches:
      - main
jobs:
  checkout:
    runs-on: [self-hosted]
    name: Checkout Code
    steps:
    - run: python3 /pw/storage/PWscripts/FV3checkoutStartClusters.py $GITHUB_REF
    
  build:
    runs-on: [self-hosted]
    name: SOLO SHiELD build
    needs: [checkout]
    strategy:
      fail-fast: true
      max-parallel: 3
      matrix:
        runpath: [/pw/storage/PWscripts]
        runscript: [FV3swStartClusters.py, FV3nhStartClusters.py, FV3hydroStartClusters.py]
    steps:
      - env:
          RUNPATH: ${{ matrix.runpath }}
          RUNSCRIPT: ${{ matrix.runscript }}
        run: python3 $RUNPATH/$RUNSCRIPT $GITHUB_REF
        
  test:
    runs-on: [self-hosted]
    name: SOLO SHiELD test suite
    needs: [checkout, build]
    strategy:
      fail-fast: false
      max-parallel: 3
      matrix:
        runpath: [/pw/storage/PWscripts]
        runscript: [FV3C128r20.solo.superCStartClusters.py]
    steps:
      - env:
          RUNPATH: ${{ matrix.runpath }}
          RUNSCRIPT: ${{ matrix.runscript }}
        run: python3 $RUNPATH/$RUNSCRIPT $GITHUB_REF
        
  shutdowncluster:
    runs-on: [self-hosted]
    name: Shutdown cluster
    if: always()
    needs: [checkout, build, test]
    steps:
      - run: python3 /home/Lauren.Chilutti/pw/storage/PWscripts/stopClusters.py ci_fv3
